#!/usr/bin/env bash
# NoctisAPI Core — interactive setup
# ─────────────────────────────────────────────────────────────────────────────
# Usage (interactive):
#   bash setup.sh
#
# Usage (non-interactive / CI):
#   bash setup.sh --domain api.example.com --email ops@example.com --yes
#
# Options:
#   --domain DOMAIN     Public API domain (required)
#   --email EMAIL       Let's Encrypt / ACME email (required)
#   --version TAG       Docker image tag (default: latest)
#   --dir PATH          Install directory (default: script directory)
#   --yes               Skip confirmation prompt
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
INSTALL_DIR="${SCRIPT_DIR}"
ENV_FILE="${INSTALL_DIR}/.env.prod"
COMPOSE_FILE="${INSTALL_DIR}/compose/docker-compose.prod.yml"
HP_IMAGE="${HP_IMAGE:-ghcr.io/0x-unkwn0wn/noctisapi-core}"
APP_VERSION="${APP_VERSION:-latest}"
HP_PUBLIC_HOST=""
ACME_EMAIL=""
AUTO_YES=0

BOLD="\033[1m"; GREEN="\033[0;32m"; YELLOW="\033[1;33m"; CYAN="\033[0;36m"; RESET="\033[0m"
info()   { echo -e "${GREEN}==>${RESET} $*"; }
warn()   { echo -e "${YELLOW}[!]${RESET} $*"; }
prompt() { echo -e "${BOLD}$*${RESET}"; }

_ask() {
  local msg="$1" default="${2:-}" answer
  if [[ -n "$default" ]]; then
    read -r -p "  ${msg} [${default}]: " answer </dev/tty
    echo "${answer:-${default}}"
  else
    while true; do
      read -r -p "  ${msg}: " answer </dev/tty
      [[ -n "$answer" ]] && { echo "$answer"; return; }
      echo "    (required)" >&2
    done
  fi
}

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)  HP_PUBLIC_HOST="$2"; shift 2 ;;
    --email)   ACME_EMAIL="$2";     shift 2 ;;
    --version) APP_VERSION="$2";    shift 2 ;;
    --image)   HP_IMAGE="$2";       shift 2 ;;
    --dir)     INSTALL_DIR="$2"; ENV_FILE="${INSTALL_DIR}/.env.prod"; shift 2 ;;
    --yes)     AUTO_YES=1;          shift   ;;
    --help|-h)
      echo "Usage: bash setup.sh [--domain DOMAIN] [--email EMAIL] [--version TAG] [--yes]"
      exit 0 ;;
    *) echo "  Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || { echo "  ERROR: docker is not installed." >&2; exit 1; }
docker compose version >/dev/null 2>&1 \
  || { echo "  ERROR: docker compose plugin not found (requires Docker 20.10+)." >&2; exit 1; }

echo ""
echo -e "${BOLD}  NoctisAPI Core — Setup${RESET}"
echo -e "${BOLD}  ════════════════════════${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Collect required inputs
# ---------------------------------------------------------------------------
[[ -z "$HP_PUBLIC_HOST" ]] && HP_PUBLIC_HOST=$(_ask "Public API domain (e.g. api.example.com)")
[[ -z "$ACME_EMAIL" ]]     && ACME_EMAIL=$(_ask     "Let's Encrypt email")

HP_SEED=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
          || openssl rand -hex 32)

# ---------------------------------------------------------------------------
# Summary + confirmation
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}──────────────────────────────────────────────${RESET}"
echo -e "${BOLD}  NoctisAPI Core — Configuration Summary${RESET}"
echo -e "${BOLD}──────────────────────────────────────────────${RESET}"
echo -e "  Image      : ${HP_IMAGE}:${APP_VERSION}"
echo -e "  API domain : ${HP_PUBLIC_HOST}"
echo -e "  ACME email : ${ACME_EMAIL}"
echo -e "  Install    : ${INSTALL_DIR}"
echo -e "${BOLD}──────────────────────────────────────────────${RESET}"
echo ""

if [[ "$AUTO_YES" -eq 0 ]]; then
  prompt "Proceed? [y/N]"
  read -r yn </dev/tty
  [[ "$yn" =~ ^[Yy]$ ]] || { echo "  Aborted."; exit 0; }
fi

# ---------------------------------------------------------------------------
# Write .env.prod (skip if already exists)
# ---------------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
  info ".env.prod already exists — skipping (delete and re-run to reconfigure)"
else
  mkdir -p "${INSTALL_DIR}/data"
  cat > "$ENV_FILE" <<ENVEOF
# NoctisAPI Core — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
APP_ENV=prod
APP_VERSION=${APP_VERSION}
HP_IMAGE=${HP_IMAGE}
DATABASE_URL=sqlite+pysqlite:////data/honeypot.db
HP_PUBLIC_HOST=${HP_PUBLIC_HOST}
ACME_EMAIL=${ACME_EMAIL}
HP_SEED=${HP_SEED}
LOG_LEVEL=info
ENVEOF
  chmod 600 "$ENV_FILE"
  info ".env.prod written (mode 600)"
fi

# ---------------------------------------------------------------------------
# Start
# ---------------------------------------------------------------------------
info "Starting NoctisAPI Core…"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --remove-orphans
docker image prune -f >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}NoctisAPI Core is running!${RESET}"
echo ""
echo -e "  API:         ${CYAN}https://${HP_PUBLIC_HOST}${RESET}"
echo -e "  Admin panel: ${CYAN}http://127.0.0.1:9001${RESET}  (SSH tunnel: ssh -L 9001:localhost:9001 user@${HP_PUBLIC_HOST})"
echo -e "  Logs:        ${CYAN}docker compose -f ${COMPOSE_FILE} --env-file ${ENV_FILE} logs -f app${RESET}"
echo -e "  Stop:        ${CYAN}docker compose -f ${COMPOSE_FILE} --env-file ${ENV_FILE} down${RESET}"
echo ""
echo "  GeoIP (optional):"
echo "    Download GeoLite2-Country.mmdb from maxmind.com and place at:"
echo "    ${INSTALL_DIR}/data/GeoLite2-Country.mmdb"
echo "    Then restart:  docker compose -f ${COMPOSE_FILE} --env-file ${ENV_FILE} restart app"
echo ""
